<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>barrage-parent</artifactId>
        <groupId>com.barrage</groupId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>barrage-cli</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.barrage</groupId>
            <artifactId>barrage-engine</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.barrage</groupId>
            <artifactId>barrage-protocol-http</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <project>
        <build>
            <plugins>
            </plugins>
        </build>

        <profiles>
            <profile>
                <id>native</id> <build>
                <plugins>
                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <version>${native.maven.plugin.version}</version>
                        <extensions>true</extensions>
                        <executions>
                            <execution>
                                <id>build-native</id>
                                <goals>
                                    <goal>compile-no-fork</goal>
                                </goals>
                                <phase>package</phase>
                            </execution>
                        </executions>
                        <configuration>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
            </profile>
        </profiles>
    </project>

</project>