---
graphName: "未命名流程"
startNodeId: "node_1772558136511_1"
nodes:
- id: "node_1772558136511_1"
  type: "START"
  name: "开始节点"
  templateRef: null
  expectedValue: null
  resultTag: null
  saveContext: false
  transition:
    next: "node_1772558137505_2"
    mode: "WAIT_FIXED"
    value: "1000"
  matchTransition: null
  mismatchTransition: null
  branches: null
- id: "node_1772558137505_2"
  type: "HTTP"
  name: "HTTP请求"
  templateRef: "/test/api1"
  expectedValue: null
  resultTag: null
  saveContext: false
  transition:
    next: "node_1772558169958_5"
    mode: "WAIT_FIXED"
    value: "1000"
  matchTransition: null
  mismatchTransition: null
  branches: null
- id: "node_1772558151752_4"
  type: "HTTP"
  name: "HTTP请求"
  templateRef: "/simulate/test2"
  expectedValue: null
  resultTag: null
  saveContext: false
  transition:
    next: "node_1772558137505_2"
    mode: "WAIT_FIXED"
    value: "1000"
  matchTransition: null
  mismatchTransition: null
  branches: null
- id: "node_1772558169958_5"
  type: "CHANCE"
  name: "概率分支"
  templateRef: null
  expectedValue: null
  resultTag: null
  saveContext: false
  transition: null
  matchTransition: null
  mismatchTransition: null
  branches:
  - weight: 50
    transition:
      next: "node_1772558151752_4"
      mode: "NO_DELAY"
      value: null
  - weight: 50
    transition:
      next: "node_1772558175911_6"
      mode: "NO_DELAY"
      value: null
- id: "node_1772558175911_6"
  type: "HTTP"
  name: "HTTP请求"
  templateRef: "/simulate/test1"
  expectedValue: null
  resultTag: null
  saveContext: false
  transition:
    next: "node_1772558137505_2"
    mode: "WAIT_FIXED"
    value: "1000"
  matchTransition: null
  mismatchTransition: null
  branches: null
